### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by samhatoum** [chipoglesby/chipoglesby.github.io#34]
Hey

Thanks for the article you wrote about [Analyzing google location history](https://www.chipoglesby.com/2018/03/2018-analyzing-google-location-historyII/)

I notice that [the data you have here ](https://raw.githubusercontent.com/chipoglesby/locationHistory/master/data/locationExample.json) shows the activity type like this:

```javascript
{  
   "heading":"122",
   "activity":[  
      {  
         "extra":[  
            {  
               "intVal":null,
               "name":null,
               "type":null
            }
         ],
         "activity":[  
            {  
               "confidence":"75",
               "type":"IN_VEHICLE"
            },
            {  
               "confidence":"10",
               "type":"ON_FOOT"
            },
            {  
               "confidence":"5",
               "type":"ON_BICYCLE"
            },
            {  
               "confidence":"5",
               "type":"STILL"
            },
            {  
               "confidence":"5",
               "type":"UNKNOWN"
            },
            {  
               "confidence":"5",
               "type":"WALKING"
            },
            {  
               "confidence":"5",
               "type":"RUNNING"
            }
         ],
         "timestampMs":"1486800273394"
      }
   ],
   "verticalAccuracy":null,
   "velocity":"35",
   "accuracy":"34",
   "longitudeE7":"116593258",
   "latitudeE7":"481265044",
   "altitude":"519",
   "timestampMs":"1486800415000"
}
```

But when I downloaded the history from Google Takeout I only see:

```javascript
{
  "locations" : [ {
    "timestampMs" : "1282654170071",
    "latitudeE7" : 515144010,
    "longitudeE7" : -2271240,
    "accuracy" : 71
  }, {
    "timestampMs" : "1282654212311",
    "latitudeE7" : 515145130,
    "longitudeE7" : -2272920,
    "accuracy" : 53
  }, {
    "timestampMs" : "1282654754325",
    "latitudeE7" : 515143040,
    "longitudeE7" : -2277160,
    "accuracy" : 51
  }
  // ...
```

Did you use a special method to download this cleaned up data?

Sorry for asking on here, I couldn't find another way to contact you :)

**Comment by chipoglesby** [comment]
@samhatoum thank you for reaching out! When you downloaded your data, did you download it as a KML file or as a GEOJSON file through the archive?

**Comment by chipoglesby** [comment]
@samhatoum I downloaded my location history again just now as a JSON file and it gives me the activity with confidence and type for 2016 through yesterday.

**Comment by samhatoum** [comment]
Thanks for getting back to me @chipoglesby. I did it again just in case and same result. Must be a difference between the way you have your location setup and mine. Perhaps I opted out of something at some point. 

Keep well!

**Comment by chipoglesby** [comment]
@samhatoum sorry to hear that, I wish it would have worked out for you.
